Upgrade the script to match benchs-root

diff --git a/scripts/benv b/scripts/benv
--- a/scripts/benv
+++ b/scripts/benv
@@ -5,16 +5,14 @@ cpuFrequency=3400
 cpuShield=1-3
 
 # processName:serviceName1:serviceName2:...
+# removing dbus-daemon:dbus.service:dbus.socket because 'unit dbus.service may be requested by dependency only'
 read -r -d '' servicesToStop << EOM
-atd:atd.service
-acpid:acpid.service:acpid.socket:acpid.path
 cron:cron.service
-dbus-daemon:dbus.service:dbus.socket
 irqbalance:irqbalance.service
 rsyslogd:rsyslog.service:syslog.socket
 EOM
 
-kernelRelease="4.9.0-0.bpo.2-amd64"
+kernelRelease="4.4.0-109-generic"
 
 # These cannot be written (IO Error)
 irqAffinitySkip=( /proc/irq/0/smp_affinity /proc/irq/2/smp_affinity )
@@ -139,12 +137,12 @@ function setFrequency() {
 
   local freqs=$(cat /proc/cpuinfo | grep MHz)
   local c=$(echo "$freqs" | grep $cpuFrequency.000 | wc -l)
-  [[ "$c" == "4" ]] ||
+  [[ "$c" == "8" ]] ||
     err "expected /proc/cpuinfo to show $cpuFrequency.000 MHz for all processors" $freqs
 
   local govs=$(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor)
   local c=$(echo "$govs" | grep userspace | wc -l)
-  [[ "$c" == "4" ]] ||
+  [[ "$c" == "8" ]] ||
     err "expected 'cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor' to show userspace for all processors" $govs
 
   logOk "CPU frequency set to $cpuFrequency MHz"
@@ -155,10 +153,46 @@ function resetFrequency() {
 
   local govs=$(cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor)
   local c=$(echo "$govs" | grep ondemand | wc -l)
-  [[ "$c" == "4" ]] ||
+  [[ "$c" == "8" ]] ||
     err "expected 'cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor' to show ondemand for all processors" $govs
 
   logOk "CPU frequency scaling governor set to 'ondemand'"
+}
+
+# CPU Turbo Boost
+ 
+function configureTurboBoost() {
+  if [[ -z $(which rdmsr) ]]; then
+      echo "msr-tools is not installed. Run 'sudo apt-get install msr-tools' to install it." >&2
+      exit 1
+  fi
+
+  if [[ ! -z $1 && $1 != "enable" && $1 != "disable" ]]; then
+      echo "Invalid argument: $1" >&2
+      echo ""
+      echo "Usage: $(basename $0) [disable|enable]"
+      exit 1
+  fi
+
+  cores=$(cat /proc/cpuinfo | grep processor | awk '{print $3}')
+  for core in $cores; do
+      if [[ $1 == "disable" ]]; then
+          sudo wrmsr -p${core} 0x1a0 0x4000850089
+      fi
+      if [[ $1 == "enable" ]]; then
+          sudo wrmsr -p${core} 0x1a0 0x850089
+      fi
+      state=$(sudo rdmsr -p${core} 0x1a0 -f 38:38)
+      if [[ $state -eq 1 ]]; then
+          echo "core ${core}: disabled"
+      else
+          echo "core ${core}: enabled"
+      fi
+  done
+
+  if [[ $1 == "disable" ]]; then
+    checkNoTurboBoost
+  fi
 }
 
 # CPU Shield
@@ -222,7 +256,7 @@ function writeIrqAffinity() {
   local save=$2
   [[ $save == 1 ]] && echo "$f:$(cat $f)" > $irqAffinityFile
   sudoWrite 1 $f
-  [[ $(cat $f) == 1 ]] ||
+  [[ $(cat $f) == "01" ]] ||
     err "failed to set interrupt affinity of $f to 1"
 }
 
@@ -274,11 +308,15 @@ function parseArgs() {
 
   optServices=1
   optFrequency=1
+  optTurboBoost=1
   optShield=1
   optIrqAffinity=1
 
   while [[ $# -gt 0 ]]; do
     case "$1" in
+      -nb)
+        optTurboBoost=0
+        ;;
       -ns)
         optServices=0
         ;;
@@ -306,21 +344,25 @@ case $mode in
   set)
     echo "Checking machine configuration"
     checkKernelRelease
-    checkNoHyperThreading
-    checkNoTurboBoost
-    checkNoNuma
     checkNoPstate
+    # checkNoHyperThreading
     checkRunningProcesses
 
+    # We don't want to check that NUMA is disable since we'll benchmark parallel compilation
+    # checkNoNuma
+
     echo "Setting benchmarking environment"
-    [[ $optServices    -eq 1 ]] && stopServices
     [[ $optFrequency   -eq 1 ]] && setFrequency
-    [[ $optShield      -eq 1 ]] && setupShield
+    [[ $optTurboBoost  -eq 1 ]] && configureTurboBoost disable
+    [[ $optServices    -eq 1 ]] && stopServices
+    # Don't run the cpu shield because we want to benchmark parallel compilation
+    # [[ $optShield      -eq 1 ]] && setupShield
     [[ $optIrqAffinity -eq 1 ]] && setupIrqAffinity
     ;;
 
   reset)
     echo "Resetting benchmarking environment"
+    configureTurboBoost enable
     resetIrqAffinity
     resetShield
     resetFrequency
